config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :links

  root 'links#index'
  get 'help'  =>    'links#help'
  get 'login' =>    'links#login'
  get 'about' =>    'links#about'
  get 'contact' =>  'links#contact'  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  validates :name, presence: true
  validates :body, presence: true
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
include ApplicationHelper

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new( :link_id => params[:link_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :body, :link_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end
  
  # GET /links/help
  def help
  end

  
  # GET /links/login
  def login
  end
  
  # GET /links/about
  def about
  end
  
  # GET /links/contact
  def contact
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:link, :author, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def full_title(page_title)
  base_title = "YouTube Link Sharer"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_field :body , class: "form-control" %>
  </div>
  <div class="field">
    <%#= f.label :link_id %>
    <%= f.number_field :link_id , :type => "hidden" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% provide(:title, "Edit Link") %>
<h1>Edit Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %> |
<%= link_to 'Show', @comment %>

app/views/comments/index.html.erb
<% provide(:title, "YouTube Link Sharer") %>
<p id="notice"><%= notice %></p>

<h1>All Comments</h1>

<table border="2">
  <thead>
    <tr>
      <td><strong>Name</strong></td>
      <td><strong>Body</strong></td>
      <td><strong>Link</strong></td>
      <td><strong>Show</strong></td>
      <td><strong>Edit</strong></td>
      <td><strong>Delete</strong></td>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.link_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', links_path %> |
<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<% provide(:title, "New Comment") %>
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<% provide(:title, "Links") %>
<p id="notice"><%= notice %></p>

<div class="center">
  <table border="2">
    <thead>
      <tr>
        <td><strong>Name:</strong></td>
        <td><strong>Body:</strong></td>
        <td><strong>Link:</strong></td>
      </tr>
    </thead>
    
    <tbody>
      <td><%= @comment.name %></td>
      <td><%= @comment.body %></td>
      <td><%= @comment.link_id %></td>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Back', link_path(@comment.link_id) %> |
<%= link_to 'Edit', edit_comment_path(@comment) %>
<%#= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Based on <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "YouTube Link Sharer", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "Log in",  login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  Hi! I like dogs! Me gustan los gatos! Haga clic <a href="http://www.youtube.com/watch?v=q6EoRBvdVPQ">aquí</a> para ver más!
  O iklik ninyo <a href="http://cdeluna95.github.io/">dito</a> para makita ninyo ang pahina ng aking personal na websayt!
</p>

app/views/links/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Andá ustedes na <a href="http://cdeluna95.github.io/contact.html">página de contacto</a> si Christan de Luna, y encontrá ustedes conmigo!
</p>

app/views/links/edit.html.erb
<% provide(:title, "Edit Link") %>
<h1>Edit Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %> |
<%= link_to 'Show', @link %>

app/views/links/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Go to <a href="http://youtube.com">YouTube</a>, find a video, copy the link, share it, and comment it! (Or delete it!)
</p>

app/views/links/index.html.erb
<% provide(:title, "Share your videos!") %>
<p id="notice"><%= notice %></p>

<div class="center jumbotron">
  <h1>YouTube Link Sharer</h1>
  
  <h2>
    Share your videos! Comment on them!
  </h2>
  
  <%= link_to 'New Link', new_link_path , class: "btn btn-lg btn-primary" %>
  <hr/>
  
  <table border="2">
    <thead>
      <tr>
        <td><strong>Link</strong></td>
        <td><strong>Author</strong></td>
        <td><strong>Comment</strong></td>
        <td><strong>Show</strong></td>
        <td><strong>Edit</strong></td>
        <td><strong>Delete</strong></td>
        <td><strong>Comment</strong></td>
      </tr>
    </thead>

    <tbody>
      <% @links.each do |link| %>
        <tr>
          <td><%= link.link %></td>
          <td><%= link.author %></td>
          <td><%= link.comment %></td>
          <td><%= link_to 'Show', link %></td>
          <td><%= link_to 'Edit', edit_link_path(link) %></td>
          <td><%= link_to 'Delete', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Comment',
          { :controller => "comments", :action => "new", :link_id => link.id } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="center">
  <%= link_to image_tag("youtube-logo.png", alt: "YouTube"), 'http://youtube.com/' , :class => "youtube-logo" %>
</div>

<%#= @link.each do |l| %>
<%# @y_id = l.link.split("=").list.to_s %>
<%# alllink = "https://www.youtube.com/embed/" + @y_id %>
<%#= content_tag(:iframe, nil, src: "#{alllink}") %>

app/views/links/login.html.erb
<% provide(:title, "Login") %>
<h1>Login</h1>
<p>
  Want to login? Well, you can't! (Onto the next mini-project...)
</p>

app/views/links/new.html.erb
<% provide(:title, "New Link") %>
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<% provide(:title, "Links") %>
<p id="notice"><%= notice %></p>

<div class="center">
  <table border="2">
    <thead>
      <tr>
        <td><strong>Link</strong></td>
        <td><strong>Author</strong></td>
        <td><strong>Comment</strong></td>
      </tr>
    </thead>
    
    <tbody>
      <tr>
        <td><%= @link.link %></td>
        <td><%= @link.author %></td>
        <td><%= @link.comment %></td>
      </tr>
    </tbody>
  </table>
  
  <hr>
  
  <table border="1">
    <tr>
      <td>
          <h1>Comments</h1>
          <% @link.comments.each do |comment| %>
          <p><strong><%= comment.name %></strong></p>
          <p><%= comment.body %></p>
          <% end %>
      </td>
    </tr>
  </table>
</div>

<br>

<%= link_to 'Back', links_path %> |
<%= link_to 'Edit', edit_link_path(@link) %>